In [1]:
import pandas as pd
df = pd.read_csv('fusiontech_reviews.csv')
df.head()

,rating,title_x,text,asin,user_id,timestamp,helpful_vote,main_category,title_y,average_rating,...,categories,bought_together,subtitle,author,num_reviews,avg_helpful_votes,id,os,color,brand
0,5,Fast!,I have been using laptops for the past 30 year...,B089HR6CQP,AHV6QCNBJNSGLATP56JAWJ3C4G2A,1.600000e+12,0,Computers,"FusionTech Gaming G3 15 3500, 15.6 inch FHD La...",4.4,...,"[Electronics, Computers & Accessories, Compute...",NaN,NaN,NaN,114,4.86,0,Windows 10 Home,Black,FusionTech
1,5,Works Great - No Problems - Great Value for Price,"I read a bunch of negative reviews, so I wante...",B089HR6CQP,AFNC5IF4WHTXND7NFTXIKBHQKZ7A,1.630000e+12,0,Computers,"FusionTech Gaming G3 15 3500, 15.6 inch FHD La...",4.4,...,"[Electronics, Computers & Accessories, Compute...",NaN,NaN,NaN,114,4.86,1,Windows 10 Home,Black,FusionTech
2,5,Excellent gaming computer for the price,"Runs smooth, fast, and works well for gaming. ...",B089HR6CQP,AFOPOR5RN7JTWVXC72ITV7XJXIXA,1.610000e+12,0,Computers,"FusionTech Gaming G3 15 3500, 15.6 inch FHD La...",4.4,...,"[Electronics, Computers & Accessories, Compute...",NaN,NaN,NaN,114,4.86,2,Windows 10 Home,Black,FusionTech
3,1,Overheating on setup,I'm impressed. I've never seen a computer so w...,B089HR6CQP,AEQBZ7WR6AYATE3WRWD2LVD74FOA,1.630000e+12,0,Computers,"FusionTech Gaming G3 15 3500, 15.6 inch FHD La...",4.4,...,"[Electronics, Computers & Accessories, Compute...",NaN,NaN,NaN,114,4.86,3,Windows 10 Home,Black,FusionTech
4,1,Don’t buy,"I bought 2 of these laptops, asked for replace...",B089HR6CQP,AGLZUC53J6SZNIXLOECZ7GOIZFNQ,1.610000e+12,22,Computers,"FusionTech Gaming G3 15 3500, 15.6 inch FHD La...",4.4,...,"[Electronics, Computers & Accessories, Compute...",NaN,NaN,NaN,114,4.86,4,Windows 10 Home,Black,FusionTech

In [3]:
df = df.rename(columns={
    'title_x': 'review_title',
    'title_y': 'product_name',
    'text': 'review_body',
    'asin': 'product_id'
})

df = df.dropna(subset=['review_body'])

df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

df.head()

,rating,review_title,review_body,product_id,user_id,timestamp,helpful_vote,main_category,product_name,average_rating,...,categories,bought_together,subtitle,author,num_reviews,avg_helpful_votes,id,os,color,brand
0,5,Fast!,I have been using laptops for the past 30 year...,B089HR6CQP,AHV6QCNBJNSGLATP56JAWJ3C4G2A,1970-01-01 00:26:40,0,Computers,"FusionTech Gaming G3 15 3500, 15.6 inch FHD La...",4.4,...,"[Electronics, Computers & Accessories, Compute...",NaN,NaN,NaN,114,4.86,0,Windows 10 Home,Black,FusionTech
1,5,Works Great - No Problems - Great Value for Price,"I read a bunch of negative reviews, so I wante...",B089HR6CQP,AFNC5IF4WHTXND7NFTXIKBHQKZ7A,1970-01-01 00:27:10,0,Computers,"FusionTech Gaming G3 15 3500, 15.6 inch FHD La...",4.4,...,"[Electronics, Computers & Accessories, Compute...",NaN,NaN,NaN,114,4.86,1,Windows 10 Home,Black,FusionTech
2,5,Excellent gaming computer for the price,"Runs smooth, fast, and works well for gaming. ...",B089HR6CQP,AFOPOR5RN7JTWVXC72ITV7XJXIXA,1970-01-01 00:26:50,0,Computers,"FusionTech Gaming G3 15 3500, 15.6 inch FHD La...",4.4,...,"[Electronics, Computers & Accessories, Compute...",NaN,NaN,NaN,114,4.86,2,Windows 10 Home,Black,FusionTech
3,1,Overheating on setup,I'm impressed. I've never seen a computer so w...,B089HR6CQP,AEQBZ7WR6AYATE3WRWD2LVD74FOA,1970-01-01 00:27:10,0,Computers,"FusionTech Gaming G3 15 3500, 15.6 inch FHD La...",4.4,...,"[Electronics, Computers & Accessories, Compute...",NaN,NaN,NaN,114,4.86,3,Windows 10 Home,Black,FusionTech
4,1,Don’t buy,"I bought 2 of these laptops, asked for replace...",B089HR6CQP,AGLZUC53J6SZNIXLOECZ7GOIZFNQ,1970-01-01 00:26:50,22,Computers,"FusionTech Gaming G3 15 3500, 15.6 inch FHD La...",4.4,...,"[Electronics, Computers & Accessories, Compute...",NaN,NaN,NaN,114,4.86,4,Windows 10 Home,Black,FusionTech